Feature/toroidal mesh from polygon
cherab/core pull request #365
Opened 2022-03-15 16:05 UTC by wave46

Added `toroidal_mesh_from_polygon()` for making mesh not fully-360 degrees axysimmetric elements and made `axisymmetric_mesh_from_polygon()` as its wrapper.

2022-03-23 21:26 UTC, vsnever requested changes
Thanks for this contribution, @wave46. I think it's good to have some compatibility with ToFu meshes.

Can you add toroidal_mesh_from_polygon to `docs/source/tools/primitives.rst` and update the `CHANGELOG.md`?

2022-03-23 21:26 UTC, vsnever commented on cherab/tools/primitives/axisymmetric_mesh.pyx
>      Generates an Raysect Mesh primitive from the specified 2D polygon.
The only reason to keep this function is for backwards compatibility. I think we can add a deprecation warning. Could you add the following text to the beginning of the docstring?
```
.. deprecated:: 1.4.0
       Use `toroidal_mesh_from_polygon` with `toroidal_extent=360` instead.
```

2022-03-25 12:02 UTC, jacklovell requested changes
Thanks for this @wave46. I have a couple of minor comments on the code which should be simple to fix, and a more general conceptual comment.

We actually need to be a little bit careful about the `toroidal_extent=360` case, as it does produce a different shape (no end faces). It also I think is likely to serve a different purpose: its use case in the past has been to easily construct a 3D first wall from a 2D limiting surface (from EFIT, originally, but also for geometry from 2D modelling codes such as SOLPS) as a quick and dirty approximation in the absence of proper 3D CAD. In contrast, the new `toroidal_mesh_from_polygon` appears to be more geared towards toroidal extrusions of smaller parts of the PFCs and is clearly making more of an effort at fidelity in the absence of CAD than a simple axisymmetric approximation. From a code-reuse perspective having `axisymmetric_mesh_from_polygon` be a special case of `toroidal_mesh_from_polygon` is a good thing, but I worry it'll be less obvious for end users if we deprecate/remove `axisymmetric_mesh_from_polygon` entirely.

To summaries this rambling, I think what I'm getting at is "a function should do one thing and do it well". My question is whether making an axisymmetric mesh can be considered sufficiently different from making a toroidal extrusion to deserve to keep its own function, or whether as @vsnever suggests they're ultimately the same thing from an end-user's perpsective.

2022-03-25 16:26 UTC, vsnever commented
I agree with @jacklovell, the fact that `axisymmetric_mesh_from_polygon` is now a wrapper, does not mean it should be deprecated. Let's keep it, but in this case `toroidal_extent` indeed should be a positional argument with no default value.

Also, @wave46, could you please add a check for `toroidal_extent` range:  `0 < toroidal_extent <= 360`?

2022-04-04 11:58 UTC, jacklovell approved these changes

2022-04-04 11:59 UTC, merged

2022-04-04 11:59 UTC, jacklovell commented
Thanks for the contribution @wave46