Add Zeeman splitting and Doppler broadening to StarkBroadenedLine and move line shapes models to a dedicated submodule
cherab/core pull request #400
Opened 2023-01-19 15:32 UTC by vsnever

This PR fixes #393 and #396.

1. The line shape models are moved to a separate submodule following the file structure proposed in #396. This change does not affect the user code.
2. The `StarkBroadenedLine` now takes into account Zeeman splitting and Doppler broadening and uses `ZeemanLineShapeModel` as a base class.
    - Following [B. Lomanowski et al](https://doi.org/10.1088/0029-5515/55/12/123028), Zeeman and Stark effects are considered independently, namely, each Zeeman feature is a Stark-Doppler line. This is a simplification and in the future we may consider switching to multi-parametric fit of the [J. Rosato et al](https://doi.org/10.1016/j.jqsrt.2016.10.005) model.
    - Unlike [B. Lomanowski et al](https://doi.org/10.1088/0029-5515/55/12/123028), the convolution of Stark and Doppler profiles is replaced with the weighted sum to speed up computations. Both the weight of the Stark profile and the FWHM of the resulting line shape are fitted to match the exact convolution. See #393 for analysis of accuracy.
    - Unlike [B. Lomanowski et al](https://doi.org/10.1088/0029-5515/55/12/123028), where the ADAS603 data is used for the Zeeman structure, here the splitting is modelled as a simple triplet. It seems superfluous to consider the exact fine structure of atomic levels in a magnetic field without taking into account the interplay of the Zeeman and Stark effects. In addition, ADAS603 data is not publicly available.

Additional changes:
- The function `add_lorentzian_line()` is added by analogy to `add_gaussian_line()`
- The method `show_supported_transitions()` of `StarkBroadenedLine` and `ParametrisedZeemanTriplet` has been made a class method, because the user cannot initialise instants without knowing what transitions are supported by these classes.
- The demo `stark_broadening.py` now plots in logscale to show the Lorentzian nature of the spectral line wings.
- The new demo `stark_zeeman.py` is added to show the Zeeman splitting of the Stark-broadened line. The plasma parameters are set the same as in Figure 2 in [B. Lomanowski et al](https://doi.org/10.1088/0029-5515/55/12/123028).
- The `test_lineshapes.py` is updated to reflect the changes in `StarkBroadenedLine`.
- All related documentation is updated.

2023-02-17 17:04 UTC, jacklovell requested changes
Looks good. Test coverage, documentation and demo provision is good for the new additions. Since the beam line shape classes have also been moved, could you add some tests for both `BeamLineShapeModel` and `BeamEmissionMultiplet` which pass both before and after the refactoring too, just to guarantee no backwards incompatibility?

2023-04-11 21:25 UTC, vsnever commented on cherab/core/model/lineshape/stark.pyx
> +    }
Done. The data is moved to `cherab/core/atomic/data` and new methods `zeeman_triplet_parameters` and `stark_model_coefficients` are added to the `AtomicData` interface. Now the `LineShapeModel` and `BeamLineShapeModel` have `AtomicData` as an additional initialisation argument and as an attribute. This argument is provided by the `PlasmaModel` or the `BeamModel`, so user code should not be affected, except perhaps in some tests when the line shape models are used stand-alone.

Please consider the implementation of `zeeman_triplet_parameters` and `stark_model_coefficients` in the core `AtomicData` interface only as a workaround until [the refactoring of the atomic data repository](https://github.com/cherab/core/pull/377) is complete. Proper read-modify-write functionality for all the default data will be added in #377. I hope, we'll have both this and #377 in the same release.

2023-04-11 21:26 UTC, vsnever commented on cherab/core/model/lineshape/zeeman.pyx
> +    }
Done.

2023-04-11 21:30 UTC, vsnever commented
> Looks good. Test coverage, documentation and demo provision is good for the new additions. Since the beam line shape classes have also been moved, could you add some tests for both BeamLineShapeModel and BeamEmissionMultiplet which pass both before and after the refactoring too, just to guarantee no backwards incompatibility?

Thanks for the review. I added a test for `BeamEmissionMultiplet`. And `BeamLineShapeModel` is just a virtual class.

2024-08-01 16:13 UTC, jacklovell approved these changes

2024-08-01 16:18 UTC, merged