WIP: Improve regularisation documentation and add ADMT demo
cherab/core pull request #427
Opened 2024-03-11 14:56 UTC by jacklovell

* Add a Regularisation section to the tomography documentation, describing the functionality inside the admt_utils module.
* Fixup the docstrings in admt_utils.
* Add calculation of "skewed" second derivative operators, which operate along the diagonals of the grid.
* Add a bolometer diagonstic system to Generomak.
* Add a new example using the Generomak bolometers and the regularisation operators to perform isotropic and ADMT inversions.

Fixes #382

2024-07-18 20:29 UTC, vsnever requested changes
Thanks @jacklovell, very valuable demo. A similar regularisation is used in ITER divertor bolometry to reconstruct the radiation power density profile. Generomak also receives the first diagnostics, which in itself is great.

I think the changelog should reflect that this demo has been added, and also that the bolometric diagnostic model has been added to Generomak.

I also have some comments and a few suggestions.

2026-06-17 14:35 UTC, jacklovell commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
The interface you propose is indeed cleaner for the specific case of a regular rectangular grid, but we need to preserve backwards compatibility and also support non-regular grids such as the `ToroidalVoxelGrid` - which doesn't have to be rectangular - albeit with rectangular cross sections for individual voxels.

I'll look at vectorising the function but in order to support a ragged grid it might not be possible: for a ragged grid it was significantly simpler to just write out the loop. And it's only O(ncells) not O(ncells^2) so the performance hit isn't that bad for an operation which only needs to be done once.

At the very least, the derivative operators can be made sparse which will help with memory usage for large `ncells`.

2026-07-21 13:35 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +BOX_WIDTH = 0.1
Redefined bow_width

2026-07-21 13:36 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +FOIL_SEPARATION = 0.00508  # 0.2 inch between foils
Could this be simply 5 mm to keep metric units?

2026-07-21 13:38 UTC, skuba31 commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
Would it make sense to have a simpler easily readable function for regular grids as Vlad suggests and another one with irregular voxels in mind?

2026-07-21 14:09 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +    The camera consists of a box with a rectangular slit and 4 sensors,
I find it a bit confusing to use word "sensor" for a pack of bolometer foils. To me, it feels a bit like a synonym for foil. I am more used to word (bolometer) module to describe a common housing for multiple foils. I do not find this to be a significant issue as realise this is mostly based on personal preference, I add this comment just for consideration.

2026-07-21 15:51 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +    The camera consists of a box with a rectangular slit and 4 sensors,
The 4-channel module is also commonly called the "bolometer head" in the literature (e.g. A. Hubert et al. EFDA-JET-CP(06)04-15 and Y. M. Duan et al EPS 2011). The paper which introduced the 4-channel bolometer design (Mast et al RSI 1991) refers to it as a "bolometer module" or "4-array." We call them 4-channel sensors at MAST-U to distinguish from the individual foils, but I have no strong preference on naming: this terminology is specific to the demo and has no impact on the rest of the bolometer API.

2026-07-21 15:51 UTC, jacklovell commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
I don't know that 2 functions will be any easier to read than 1 function.

2026-07-21 15:53 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +FOIL_SEPARATION = 0.00508  # 0.2 inch between foils
The bolometer sensors (heads, modules, assemblies) supplied by IPT Albrecht which make up >95% of the world's bolometer arrays use 0.2 inches rather than 5 mm between foils. So while nice round numbers would be aesthetically pleasing, these dimensions are more relevant to end users. It's also why the width and height are 1.3 mm and 3.8 mm respectively: these match the dimensions of the Albrecht foils.

2026-07-22 06:08 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +    The camera consists of a box with a rectangular slit and 4 sensors,
I see, then I would use either head or module. The intended audience is very likely familiar with these papers and it could make it easier for them to navigate the demo.

2026-07-22 06:12 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +FOIL_SEPARATION = 0.00508  # 0.2 inch between foils
Oh, I did not know that IPT is using separation in inches. I agree that the number should not be changed. I was suspecting an inspiration by an existing system, but the number with hundredths of mm surprised me. Do you think it would make sense to acknowledge the inspiration in the docs or comments?

2026-07-22 07:10 UTC, skuba31 commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
It is not only about having two function, I should have explained better. In his comments, Vlad is suggesting that a function assuming regular grid would make the demo simpler and therefore the use on regular grids in general. In my experience, regular grids are by far the most common choice these days.

So the question is, whether having a function with limited scope tailored for the most common use case outweighs the longer source code with two functions, where the second would be more general.

Or a wrapper function that would handle the mapping from regular grid into general could be created to simplify the most common use case.

Alternatively I have a rather longer term idea for consideration. Given that inversions are not the primary aim of Cherab, inversion related parts (all or the more advanced ones) could be relocated to a dedicated package.

2026-07-22 09:16 UTC, skuba31 commented on cherab/tools/inversions/nnls.py
> +def invert_sparse_regularised_nnls(w_matrix, b_vector, alpha=0.01, tikhonov_matrix=None, **kwargs):
Contrary to the opinion I expressed at the TMC meeting, I now think that the sparse inversion and sparse output of derivative operators can stay in this PR if properly included into the description.

2026-07-30 14:47 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +FOIL_SEPARATION = 0.00508  # 0.2 inch between foils
I've added a brief explanatory comment saying what inspired these values, without naming any particular company but appealing to their common use.

2026-07-30 14:47 UTC, jacklovell commented on cherab/tools/inversions/nnls.py
> +def invert_sparse_regularised_nnls(w_matrix, b_vector, alpha=0.01, tikhonov_matrix=None, **kwargs):
Added to the changelog.

2026-07-30 16:19 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +    ):
Done, defined globally so users can query the properties themselves instead of burying it inside a function.

2026-07-30 16:28 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +    The camera consists of a box with a rectangular slit and 4 sensors,
I've gone with "bolometer head" in the docstrings and comments, and the shortened version "head" in the code as it's quicker for users to type.

2026-07-31 13:18 UTC, jacklovell commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
I've remembered now why I implemented it this way.

We've historically used "masked" voxel grids for doing bolometry inversions in the machine-specific subpackages: examples for [JET](https://github.com/cherab/jet/blob/70b845cc0bac6fa4a92159805a253938cad775b1/demos/diagnostic/kb5/grid_generation.py), [MAST-U](https://github.com/cherab/mastu/blob/821396b1b8448187254e0d217431974f1dd474cd/examples/bolometry/grid_generation/make_sxdl_rectilinear_grid.py) and [AUG](https://github.com/cherab/aug/blob/c37f9dbd9c374eb4c913952fb930eeba1fe3aecd/cherab/aug/bolometry/grid_construction/make_grid_laplacian.py). For a voxel grid there is a measurable performance advantage to omitting voxels which aren't within the first wall of the machine, which leads to "ragged" arrays of voxels which roughly follow the contours of the first wall/limiting surface.

Since this formulism is already in widespread use I think it's important to support it for both new and existing users. And since the Ray Transfer Matrix formulism specialises this more general formulism to a regular grid it's easy to support it too (as the demo shows). I don't think it would be as straightforward to do the reverse: write a function expecting a regular grid and have end users convert ragged grids into the correct form.

I could I suppose also show the usage with a `ToroidalVoxelGrid`, which would even more closely match what the existing packages do. But that case is sufficiently trivial (all these machine packages give exactly the inputs required for this function) that I think users would be able to work it our for themselves.

2026-07-31 14:04 UTC, jacklovell commented on demos/observers/bolometry/admt_tomographic_inversion.py
> +voxel_vertices = voxel_centres[:, None, :] + vertex_displacements[None, :, :]
TBF quite a bit of this code could have been skipped if I hadn't missed the obvious fact that the 2D-to-1D map is simply the inverse of the 1D-to-2D map:
```python
grid_index_2d_to_1d_map = {rz: k for (k, rz) in grid_index_1d_to_2d_map.items()}
```
And vice versa.

So actually, only one of the 2D-to-1D or 1D-to-2D maps is required and the other can always be computed trivially, without loss of generality. I'll make `generate_derivative_operators` optionally accept only one of these two arguments, and automatically compute the other if the user don't already provide both. That'll simplify the demo too while maintaining backwards compatibility.

2026-07-31 14:14 UTC, jacklovell commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
The other big advantage of the looping method over the vectorized method is memory efficiency when `sparse=True` is passed through, which is important for computing the operators for large grids on memory-limited machines. This alone I think makes it worthwhile keeping the existing looping function. Hopefully with the added comments it'll be a bit easier to follow now, which I think was the essence of Vlad's original comment.

2026-07-31 16:15 UTC, jacklovell commented on demos/observers/bolometry/admt_tomographic_inversion.py
> +voxel_vertices = voxel_centres[:, None, :] + vertex_displacements[None, :, :]
8e2a399 allows passing only 1 voxel mapping to the derivative operators generator function, which significantly simplifies this for the end user even in the Ray Transfer case.

2026-07-31 16:23 UTC, jacklovell commented
I've implemented the changes from both reviews now: thanks to @vsnever and @skuba31. I am going to hold firm on the formulism in `generate_derivative_operators` though, as I think the benefits of sparseness and explicitness outweigh any potential performance gains or loss of generality of the vectorized version Vlad proposed before the iterative improvements from the reviews. As a compromise the function is now better commented and the interface is a bit easier to use for callers as reflected in the demo.

Once this is approved I'll do a squash merge as the commit history is longer than necessary to keep going forwards.

2026-08-03 15:44 UTC, skuba31 commented on cherab/tools/inversions/admt_utils.py
>      Generate the first and second derivative operators for a regular grid.
I see the backward compatibility and existing codes as the most important reason for keeping the approach you proposed. The memory efficiency is a nice bonus.

I think that having an explicit example for trivial code is worth it should the code be used frequently. Do you see the use with `ToroidalVoxelGrid` as a sort of "default" approach? If so, I would be in favor of including that example. It could be a comment in existing demo if that is possible, not necessarily entirely new one.

2026-08-04 07:00 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +# poloidal rotations
I see the advantages of grouping a property for all cameras, but it is a bit confusing for me to navigate in. I found it more natural to group properties by camera, so that it is simpler to see where the camera is, without need to search through multiple sections of the code.

2026-08-04 07:19 UTC, skuba31 commented on demos/observers/bolometry/admt_tomographic_inversion.py
> +# Define the centres of each voxel, as an (nx, ny, 2) array.
I would suggest renaming `nx` to `nr` and `ny` to `nz`. Using `ny` for number of voxels in vertical direction could cause some confusion as in tokamaks the `y` axis typically lies in midplane. It also results in somewhat awkward naming in pairs `cell_r`, `cell_dx` defined by `nx` and `cell_z`, `cell_dz` defined by `ny`.

2026-08-04 07:33 UTC, skuba31 commented on demos/observers/bolometry/admt_tomographic_inversion.py
> +voxel_vertices = voxel_centres[:, None, :] + vertex_displacements[None, :, :]
I think it is fine to leave these few extra lines here now. I suppose that this code could be simplified by adding properties or methods to grid classes in the future.

2026-08-04 08:01 UTC, skuba31 reviewed
Nice work @jacklovell . I think that the documentation and code readability is significantly improved. The sparse support and ADMT demo are very useful additions. I have added a few minor comments for consideration before final approval.

2026-08-19 16:56 UTC, jacklovell commented on demos/observers/bolometry/admt_tomographic_inversion.py
> +# Define the centres of each voxel, as an (nx, ny, 2) array.
Good call. Done.

2026-08-19 17:18 UTC, jacklovell commented on cherab/generomak/diagnostics/bolometers.py
> +# poloidal rotations
I think this probably comes down to personal preference. The main advantage of grouping by property rather than by camera is that you can see the relative positioning of each of the cameras. For example:

```python
# poloidal rotations
CAMERA_GEOMETRY['HozPol1']['rotation_poloidal'] = 30
CAMERA_GEOMETRY['HozPol2']['rotation_poloidal'] = -30
CAMERA_GEOMETRY['VertPol']['rotation_poloidal'] = -90
CAMERA_GEOMETRY['TanMid1']['rotation_poloidal'] = 0
CAMERA_GEOMETRY['TanPol1']['rotation_poloidal'] = -25
```

From this you can clearly see that the poloidal directions the two poloidal cameras point are mirrored about the horizontal plane that the tangential-midplane camera points along, the tangential-poloidal camera is pointing slightly downwards poloidally and the vertical poloidal camera is pointing straight down. So it's easy to visualise all of these cameras in the context of each other and the overall scene.

It's not as easy to visualise camera positions when grouping by camera:

```python
CAMERA_GEOMETRY['TanPol1'] = dict(
    rotation_poloidal=-25,
    rotation_toroidal=40,
    rotation_radial=0,
    origin=Point3D(2.2, 0, -0.8),
    slit_head_separation=0.15,
    head_angles=[-12, -4, 4, 12],
    head_rotations=[180, 180, 180, 180],
    toroidal_angle=15,  # avoid LFS limiters
)
```

If you're already familiar with what these translations and rotations mean then parsing the latter is OK, but it can be helpful to work out what a particular transformation means by comparing the different cameras where you have an intuitive expectation of where each one should go.

It is actually pretty trivial to print out the same representation grouped by camera:

```python
>>> from cherab.generomak.diagnostics.bolometers import CAMERA_GEOMETRY
>>> from pprint import pprint
>>> pprint(CAMERA_GEOMETRY)
{'HozPol1': {'head_angles': [22.5, 7.5, -7.5, -22.5],
             'head_rotations': [0, 0, 0, 0],
             'origin': Point3D(2.45, 0.05, 0.0),
             'rotation_poloidal': 30,
             'rotation_radial': -90,
             'rotation_toroidal': 0,
             'slit_head_separation': 0.08,
             'toroidal_angle': 10},
 'HozPol2': {'head_angles': [22.5, 7.5, -7.5, -22.5],
             'head_rotations': [0, 0, 0, 0],
             'origin': Point3D(2.45, -0.05, 0.0),
             'rotation_poloidal': -30,
             'rotation_radial': -90,
             'rotation_toroidal': 0,
             'slit_head_separation': 0.08,
             'toroidal_angle': 10},
 'TanMid1': {'head_angles': [18, 6, -6, -18],
             'head_rotations': [0, 0, 0, 0],
             'origin': Point3D(2.5, 0.0, 0.0),
             'rotation_poloidal': 0,
             'rotation_radial': 0,
             'rotation_toroidal': -40,
             'slit_head_separation': 0.1,
             'toroidal_angle': -15},
 'TanPol1': {'head_angles': [-12, -4, 4, 12],
             'head_rotations': [180, 180, 180, 180],
             'origin': Point3D(2.2, 0.0, -0.8),
             'rotation_poloidal': -25,
             'rotation_radial': 0,
             'rotation_toroidal': 40,
             'slit_head_separation': 0.15,
             'toroidal_angle': 15},
 'VertPol': {'head_angles': [36, 12, -12, -36],
             'head_rotations': [0, 0, 0, 0],
             'origin': Point3D(1.3, 0.0, 1.42),
             'rotation_poloidal': -90,
             'rotation_radial': -90,
             'rotation_toroidal': 0,
             'slit_head_separation': 0.05,
             'toroidal_angle': 0}}
```

I'll add a comment to this effect so that users who would prefer this group-by-camera representation can get it easily, without losing the benefits of the group-by-property layout in the code itself.

2026-08-20 06:00 UTC, skuba31 commented on cherab/generomak/diagnostics/bolometers.py
> +# poloidal rotations
I see your point. This is indeed based on personal preference. Given the fact it is straightforward to print parameters grouped by camera, it makes more sense to keep grouping by parameter in demo with a comment showing how to print parameters grouped by camera.

2026-08-20 06:04 UTC, skuba31 approved these changes
I consider this PR to be ready for merge now.

2026-08-20 09:10 UTC, merged