Fix incorrect docstrings for atomic rate base classes
cherab/core pull request #432
Opened 2024-04-27 09:41 UTC by vsnever

This updates the docstrings for the atomic process rate base classes and fixes 431.

2024-05-06 13:21 UTC, Mateasek approved these changes
Seems good to me

2024-05-09 16:43 UTC, jacklovell requested changes
Changing the names of the arguments is technically a breaking change for anybody passing arguments as keywords to these functions. I get that aesthetically it's nicer to have a uniform convention of `density` and `temperature` as names, but have you checked there's nowhere else in the code that calls these by keyword (may not be covered by existing unit tests)?

I'd be inclined to leave the argument names as they are and only update the docstrings.

2024-05-09 21:21 UTC, vsnever commented
Thanks for the reviews, @Mateasek, @jacklovell.

>Changing the names of the arguments is technically a breaking change for anybody passing arguments as keywords to these functions. I get that aesthetically it's nicer to have a uniform convention of density and temperature as names, but have you checked there's nowhere else in the code that calls these by keyword (may not be covered by existing unit tests)?
 I'd be inclined to leave the argument names as they are and only update the docstrings.
 
Yes, indeed, in Python positional arguments can also be passed by keyword, and changing the name of a positional argument can cause a `TypeError`. I did not think about that. I returned the arguments to their old names.

2024-05-10 10:22 UTC, jacklovell approved these changes

2024-05-10 10:23 UTC, merged