Add docstrings for ExcitationLine and RecombinationLine emission models.
cherab/core pull request #435
Opened 2024-05-13 10:42 UTC by vsnever

This adds missing docstrings for `ExcitationLine` and `RecombinationLine` emission models. This was originally part of #386, but has been moved to a separate PR.

2024-05-14 12:41 UTC, jacklovell requested changes
Nice. I suggest using raw strings to reduce the number of backslashes required, but otherwise looks good.

2024-05-14 15:26 UTC, vsnever commented on cherab/core/model/plasma/impact_excitation.pyx
> +    """
Done.

2024-05-14 15:26 UTC, vsnever commented on cherab/core/model/plasma/recombination.pyx
> +    """
Done.

2024-05-14 15:27 UTC, vsnever commented
Thanks, @jacklovell, I converted docstrings to raw string format.

2024-05-15 06:45 UTC, Mateasek approved these changes
Hi @vsnever , looks good to me, thanks for writing it.

2024-05-16 07:15 UTC, jacklovell approved these changes

2024-05-16 07:15 UTC, merged